Implemented creation of directories in the user prefix

diff --git a/install b/install
--- a/install
+++ b/install
@@ -31,10 +31,12 @@ SOFTWARE.
 
 # TODO - Implement sourcing for libraries
 
-. ./configuration.*     # Build target's local configuration files
+. ./configuration.*     # Install target's local configuration files
 . library.log.sh        # https://github.com/kz9676/library.log.sh
 
 ## Executables
+
+# System prefix
 
 if [ ! -d $application_executables_path ];
 then
@@ -58,6 +60,21 @@ do
     fi 
 done
 
+# User prefix
+
+if [ ! -d $user_executables_path ];
+then
+    log warning "User executables directory is not found - $user_executables_path"
+    log information "Creating user executables directory - $user_executables_path"
+    mkdir -p $user_executables_path
+    if [ $? = 0 ];
+    then 
+        log success "Created user executables directory - $user_executables_path"
+    else 
+        log error "Failed to create user executables directory - $user_executables_path"
+    fi 
+fi 
+
 for file in ${user_executable_files[@]};
 do
     if [ -f $file ];
@@ -68,6 +85,8 @@ do
 done
 
 ## Libraries
+
+# System prefix
 
 if [ ! -d $application_libraries_path ];
 then
@@ -91,6 +110,21 @@ do
     fi 
 done
 
+# User prefix
+
+if [ ! -d $user_libraries_path ];
+then
+    log warning "User libraries directory is not found - $user_libraries_path"
+    log information "Creating user libraries directory - $user_libraries_path"
+    mkdir -p $user_libraries_path
+    if [ $? = 0 ];
+    then 
+        log success "Created user libraries directory - $user_libraries_path"
+    else 
+        log error "Failed to create user libraries directory - $user_libraries_path"
+    fi 
+fi 
+
 for file in ${user_library_files[@]};
 do
     if [ -f $file ];
@@ -101,6 +135,8 @@ do
 done
 
 ## Configurations
+
+# System prefix
 
 if [ ! -d $application_configurations_path ];
 then
@@ -125,6 +161,21 @@ do
     fi 
 done
 
+# User prefix
+
+if [ ! -d $user_configurations_path ];
+then
+    log warning "User configurations directory is not found - $user_configurations_path"
+    log information "Creating user configurations directory - $user_configurations_path"
+    mkdir -p $user_configurations_path
+    if [ $? = 0 ];
+    then 
+        log success "Created user configurations directory - $user_configurations_path"
+    else 
+        log error "Failed to create user configurations directory - $user_configurations_path"
+    fi 
+fi 
+
 for file in ${user_configuration_files[@]};
 do
     if [ -f $file ];
@@ -135,6 +186,8 @@ do
 done
 
 ## Templates
+
+# System prefix
 
 if [ ! -d $application_templates_path ];
 then
@@ -158,6 +211,21 @@ do
     fi 
 done
 
+# User prefix
+
+if [ ! -d $user_templates_path ];
+then
+    log warning "User templates directory is not found - $user_templates_path"
+    log information "Creating user templates directory - $user_templates_path"
+    mkdir -p $user_templates_path
+    if [ $? = 0 ];
+    then 
+        log success "Created user templates directory - $user_templates_path"
+    else 
+        log error "Failed to create user templates directory - $user_templates_path"
+    fi 
+fi 
+
 for file in ${user_template_files[@]};
 do
     if [ -f $file ];
@@ -166,4 +234,36 @@ do
         cp -v ./$file $user_templates_path/$file
     fi 
 done
+
+## Logs
+
+# System prefix
+
+if [ ! -d $application_logs_path ];
+then
+    log warning "Application logs directory is not found - $application_logs_path"
+    log information "Creating application logs directory - $application_logs_path"
+    mkdir -p $application_logs_path
+    if [ $? = 0 ];
+    then 
+        log success "Created application logs directory - $application_logs_path"
+    else 
+        log error "Failed to create application logs directory - $application_logs_path"
+    fi 
+fi 
+
+# User prefix
+
+if [ ! -d $user_logs_path ];
+then
+    log warning "User logs directory is not found - $user_logs_path"
+    log information "Creating user logs directory - $user_logs_path"
+    mkdir -p $user_logs_path
+    if [ $? = 0 ];
+    then 
+        log success "Created user logs directory - $user_logs_path"
+    else 
+        log error "Failed to create user logs directory - $user_logs_path"
+    fi 
+fi 
 
