Added setup command

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -29,7 +29,42 @@ SOFTWARE.
 
 '
 
-# TODO - Add verbose output
+# TODO - Move message formatting to an external library
 
-repository_authors="$(git log --format='%an <%ae>' HEAD -n1)"  
-echo $repository_authors > ./AUTHORS
+parent_directory_name=${PWD##*/}
+source_module_name=$parent_directory_name
+info="~~> INFO:" 
+warning="~~> WARNING:" 
+error="~~> ERROR:" 
+ok="~~> OK:" 
+
+# Source module descriptors
+source_module_files=(
+    AUTHORS
+    BACKGROUND
+    BUILD
+    CHANGELOG
+    DEFECTS
+    DEPENDENCIES
+    DESCRIPTION
+    DESIGN
+    FILES
+    INSTALL
+    LICENSE
+    REQUIREMENTS
+    SOURCES
+    TASKS
+    TEST
+    VERSION
+)
+
+printf "$info Initializing $source_module_name source module...\n" >&2
+for source_module_file in ${source_module_files[@]};
+do
+   printf "$info Creating $source_module_file ...\n" >&2
+   if [ ! -f $source_module_file ];
+   then
+       touch $source_module_file 
+   fi 
+   touch $source_module_file
+done
