Implemented incremental versioning

diff --git a/version b/version
--- a/version
+++ b/version
@@ -28,8 +28,42 @@ SOFTWARE.
 
 '
 
-# TODO - Implement automated incremental versioning
+. library.logging.sh
 
 version_file_name=VERSION
 version_file_path=. 
 version_file=$version_file_path/$version_file_name
+
+increment_version() {
+    declare -a part=( ${1//\./ } )
+    declare -i carry=1
+    declare new
+
+    for (( i=${#part[@]}-1; i>=0; i-=1 ));
+    do
+        count=${#part[i]}
+        new=$((part[i]+carry))
+        [ ${#new} -gt $count ] && carry=1 || carry=0
+        [ $i -gt 0 ] && part[i]=${new: -count} || part[i]=${new}
+    done
+
+    new="${part[*]}"
+    echo -e "${new// /.}" > $version_file
+}
+
+if [ -f $version_file ];
+then
+    printf "$info Reading version ...\n" >&2
+    version="$(<$version_file)"
+    if [ -n "$version" ];
+    then
+        printf "$info Incrementing version $version ...\n" >&2
+        increment_version $version 
+    else 
+        printf "$error Failed to read previous version.\n" >&2
+        exit 1
+    fi 
+else 
+    printf "$error Failed to increment version. $version_file not found.\n" >&2
+    exit 1
+fi 
